Kmeans:Kmeans.o ClusterTree.o
	g++ -o Kmeans Kmeans.o ClusterTree.o
Kmeans.o:Kmeans.cpp
	g++ -c Kmeans.cpp
ClusterTree.o:ClusterTree.cpp
	g++ -c ClusterTree.cpp
clean:
	rm Kmeans
	rm Kmeans.o
	rm ClusterTree.o
