//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by intrusiondetectionsystem.rc
//

#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ProtocolAnalysis_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DIALOG_JIESHAO              129
#define IDD_DIALOG_F1                   129
#define IDR_MENU1                       130
#define IDR_TOOLBAR1                    131
#define IDR_TUOPAN                      133
#define IDR_AVI                         145
#define IDD_FILTER_DLG                  146
#define IDI_ICON1                       150
#define IDI_ICON4                       153
#define IDI_ICON5                       154
#define IDD_RULES                       155
#define IDI_ICON6                       156
#define IDI_ICON7                       157
#define IDB_BITMAP1                     158
#define IDI_ICON12                      164
#define IDI_ICON15                      167
#define IDI_ICON16                      168
#define IDI_ICON18                      170
#define IDI_ICON19                      171
#define IDI_ICON2                       172
#define IDI_ICON22                      174
#define IDI_ICON23                      175
#define IDI_ICON3                       177
#define IDR_TOOLBAR2                    183
#define IDR_GIF                         188
#define IDR_GIF1                        189
#define IDD_DIALOG_HELP                 190
#define IDB_BITMAP2                     191
#define IDB_BITMAP6                     201
#define IDB_BITMAP7                     203
#define IDB_BITMAP8                     204
#define IDR_MENU_LIST                   205
#define IDB_BITMAP5                     208
#define IDB_COOLDIGITCOLON              210
#define IDB_COOLDIGIT                   211
#define IDB_COOLDIGITDOT                212
#define IDB_BITMAP_TAB                  213
#define IDD_DIALOG_GRAPH                215
#define IDC_HAND1                       216
#define IDC_CURSOR1                     242
#define IDD_DIALOG_INTRUSION_ADD        244
#define IDD_DIALOG_INTRUSION_RULE       245
#define IDD_DIALOG_DEVICE               246
#define IDB_BITMAP3                     261
#define IDD_DIALOG_GRAPH_PIE            262
#define IDD_DIALOG_PARAMETER            263
#define IDI_MAINFRAME                   272
#define IDC_EDIT1                       1000
#define IDC_EDIT_FILTER                 1000
#define IDC_EDIT_RED                    1000
#define IDC_EDIT_RULE_NAME              1000
#define IDC_BUTTON1                     1001
#define IDC_CENTER                      1001
#define IDC_BUTTON_ADD_RULE             1001
#define IDC_EDIT2                       1002
#define IDC_EDIT_GREEN                  1002
#define IDC_EDIT_RULE_PROTOCOL          1002
#define IDC_BUTTON2                     1003
#define IDC_BUTTON_SHOW_HIDE            1003
#define IDC_BUTTON_DELETE_RULE          1003
#define IDC_BUTTON_PARAMETER            1003
#define IDC_BUTTON3                     1004
#define IDC_BUTTON_ABOUT                1004
#define IDC_LIST1                       1005
#define IDC_LIST_INTRUSION_RULE         1005
#define IDC_LIST_DEVICE                 1005
#define IDC_LIST_INTRUSION              1005
#define IDC_LIST_INFORMATION            1008
#define IDC_BUTTON4                     1009
#define IDC_BUTTON5                     1010
#define IDC_BUTTON_DELETE_A             1010
#define IDC_BUTTON_OPEN_DUMP_FILE       1010
#define IDC_BUTTON6                     1011
#define IDC_BUTTON_DELETE_ALL           1011
#define IDC_BUTTON_SET_FILTER           1011
#define IDC_BUTTON7                     1012
#define IDC_BUTTON8                     1013
#define IDC_BUTTON9                     1014
#define IDC_BUTTON_START                1014
#define IDC_BUTTON10                    1015
#define IDC_BUTTON_END                  1015
#define IDC_TAB1                        1017
#define IDC_LIST_ARP                    1018
#define IDC_ZUOZHE                      1019
#define IDC_MYWEB                       1020
#define IDC_MYMAIL                      1021
#define IDC_WEB                         1022
#define ID_MAIN_MYWEB                   1023
#define ID_MAIN_MYEMAIL                 1024
#define IDC_MAIL                        1025
#define IDC_BUTTON_HIDE                 1026
#define IDC_SHOCKWAVEFLASH1             1028
#define IDC_LIST_IP                     1029
#define IDC_LIST_TCP                    1030
#define IDC_LIST_UDP                    1031
#define IDC_LIST_ICMP                   1032
#define IDC_STATIC_PICTURE              1033
#define IDC_EDIT_BLUE                   1034
#define IDC_IMAGE                       1035
#define IDC_STATIC_NUMBER               1036
#define IDC_DYCREDITS                   1037
#define IDC_STATIC_M                    1038
#define IDC_STATIC_GRAPH                1039
#define IDC_STATIC_SPLIT_BMP            1040
#define IDC_LIST_INTRUSION_ALERT        1041
#define IDC_EDIT3                       1042
#define IDC_EDIT_RULE_CODE              1042
#define IDC_EDIT4                       1043
#define IDC_EDIT_RULE_DEFINATION        1043
#define IDC_EDIT5                       1044
#define IDC_EDIT_RULE_RESPONSE          1044
#define IDC_EDIT6                       1045
#define IDC_EDIT_RULE_INFORMATION       1045
#define IDC_STATIC_STATUS               1046
#define IDC_STATIC_BANQUAN              1047
#define IDC_CHECK_SAVE_DUMP_FILE        1048
#define IDC_CHECK_SHOW_PACKET_DATA      1049
#define IDC_STATIC_XUANXIANG            1050
#define IDC_LIST_ETHERNET               1053
#define IDC_STATIC_PACKET_COUNT         1054
#define IDC_CHECK_INTRUSION_DETECT      1055
#define ID_HARIKRISHNA                  32771
#define MENU_START                      32771
#define MENU_STOP                       32772
#define MENU_EXIT                       32773
#define MENU_SET_FILETER                32774
#define MENU_SET_RULES                  32775
#define MENU_HELP                       32776
#define IDD_RUN_ANOTHER                 32777
#define ID_MENU_HELP                    32777
#define ID_T_START                      32778
#define ID_T_STOP                       32779
#define ID_T_DELET_A                    32780
#define ID_T_DELETE_ALL                 32781
#define ID_T_ABOUT                      32782
#define ID_T_EXIT                       32783
#define ID_TUO_ABOUT                    32784
#define ID_TUO_XIANSHI                  32785
#define ID_TUO_SHEZHI                   32786
#define ID_TUO_EXIT                     32787
#define ID_T_HIDE                       32789
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_BUTTON32801                  32801
#define ID_MENU_QINGKONG                32802
#define ID_MENU_COLOR                   32803
#define ID_MENU_PROTOCOL                32806
#define ID_MENU_SPLIT1_SHOW             32807
#define ID_MENUITEM32808                32808
#define ID_MENU_SPLIT1_HIDE             32809
#define MENU_STOP_ALERT                 32811
#define MENU_GRAPH                      32812
#define ID_MENU_ARP                     32813
#define ID_MENU_IP                      32814
#define ID_MENU_TCP                     32815
#define ID_MENU_UDP                     32816
#define ID_MENU_ICMP                    32817
#define ID_MENU_INTRUSION_WINDOW        32818
#define ID_MENU_PACKET                  32819
#define ID_MENU_OPEN_DUMP_FILE          32820
#define ID_MENU_XUANXIANG               32821
#define ID_MENU_SET_PARAMETER           32821
#define ID_MENU_ETHERNET                32822
#define ID_MENU_INTRUSION               32823

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        273
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
